module Flags where
import Data.Text

countries :: [(Text, Text)]
countries =
    [
        ("None","None.png"),
        ("Afghanistan","Afghanistan.png"),
        ("Albania","Albania.png"),
        ("Algeria","Algeria.png"),
        ("American Samoa","American_Samoa.png"),
        ("Andorra","Andorra.png"),
        ("Angola","Angola.png"),
        ("Anguilla","Anguilla.png"),
        ("Antigua and Barbuda","Antigua_and_Barbuda.png"),
        ("Argentina","Argentina.png"),
        ("Armenia","Armenia.png"),
        ("Aruba","Aruba.png"),
        ("Australia","Australia.png"),
        ("Austria","Austria.png"),
        ("Azerbaijan","Azerbaijan.png"),
        ("Bahamas","Bahamas.png"),
        ("Bahrain","Bahrain.png"),
        ("Bangladesh","Bangladesh.png"),
        ("Barbados","Barbados.png"),
        ("Belarus","Belarus.png"),
        ("Belgium","Belgium.png"),
        ("Belize","Belize.png"),
        ("Benin","Benin.png"),
        ("Bermuda","Bermuda.png"),
        ("Bhutan","Bhutan.png"),
        ("Bolivia","Bolivia.png"),
        ("Bosnia","Bosnia.png"),
        ("Botswana","Botswana.png"),
        ("Brazil","Brazil.png"),
        ("British Virgin Islands","British_Virgin_Islands.png"),
        ("Brunei","Brunei.png"),
        ("Bulgaria","Bulgaria.png"),
        ("Burkina Faso","Burkina_Faso.png"),
        ("Burundi","Burundi.png"),
        ("Cambodia","Cambodia.png"),
        ("Cameroon","Cameroon.png"),
        ("Canada","Canada.png"),
        ("Cape Verde","Cape_Verde.png"),
        ("Cayman Islands","Cayman_Islands.png"),
        ("Central African Republic","Central_African_Republic.png"),
        ("Chad","Chad.png"),
        ("Chile","Chile.png"),
        ("China","China.png"),
        ("Christmas Island","Christmas_Island.png"),
        ("Colombia","Colombia.png"),
        ("Comoros","Comoros.png"),
        ("Cook Islands","Cook_Islands.png"),
        ("Costa Rica","Costa_Rica.png"),
        ("Côte d'Ivoire","Cote_d'Ivoire.png"),
        ("Croatia","Croatia.png"),
        ("Cuba","Cuba.png"),
        ("Cyprus","Cyprus.png"),
        ("Czech Republic","Czech_Republic.png"),
        ("Democratic Republic of the Congo","Democratic_Republic_of_the_Congo.png"),
        ("Denmark","Denmark.png"),
        ("Djibouti","Djibouti.png"),
        ("Dominican Republic","Dominican_Republic.png"),
        ("Dominica","Dominica.png"),
        ("Ecuador","Ecuador.png"),
        ("Egypt","Egypt.png"),
        ("El Salvador","El_Salvador.png"),
        ("Equatorial Guinea","Equatorial_Guinea.png"),
        ("Eritrea","Eritrea.png"),
        ("Estonia","Estonia.png"),
        ("Ethiopia","Ethiopia.png"),
        ("Falkland Islands","Falkland_Islands.png"),
        ("Faroe Islands","Faroe_Islands.png"),
        ("Fiji","Fiji.png"),
        ("Finland","Finland.png"),
        ("France","France.png"),
        ("French Polynesia","French_Polynesia.png"),
        ("Gabon","Gabon.png"),
        ("Gambia","Gambia.png"),
        ("Georgia","Georgia.png"),
        ("Germany","Germany.png"),
        ("Ghana","Ghana.png"),
        ("Gibraltar","Gibraltar.png"),
        ("Greece","Greece.png"),
        ("Greenland","Greenland.png"),
        ("Grenada","Grenada.png"),
        ("Guam","Guam.png"),
        ("Guatemala","Guatemala.png"),
        ("Guinea Bissau","Guinea_Bissau.png"),
        ("Guinea","Guinea.png"),
        ("Guyana","Guyana.png"),
        ("Haiti","Haiti.png"),
        ("Honduras","Honduras.png"),
        ("Hong Kong","Hong_Kong.png"),
        ("Hungary","Hungary.png"),
        ("Iceland","Iceland.png"),
        ("India","India.png"),
        ("Indonesia","Indonesia.png"),
        ("Iran","Iran.png"),
        ("Iraq","Iraq.png"),
        ("Ireland","Ireland.png"),
        ("Israel","Israel.png"),
        ("Italy","Italy.png"),
        ("Jamaica","Jamaica.png"),
        ("Japan","Japan.png"),
        ("Jordan","Jordan.png"),
        ("Kazakhstan","Kazakhstan.png"),
        ("Kenya","Kenya.png"),
        ("Kiribati","Kiribati.png"),
        ("Kuwait","Kuwait.png"),
        ("Kyrgyzstan","Kyrgyzstan.png"),
        ("Laos","Laos.png"),
        ("Latvia","Latvia.png"),
        ("Lebanon","Lebanon.png"),
        ("Lesotho","Lesotho.png"),
        ("Liberia","Liberia.png"),
        ("Libya","Libya.png"),
        ("Liechtenstein","Liechtenstein.png"),
        ("Lithuania","Lithuania.png"),
        ("Luxembourg","Luxembourg.png"),
        ("Macao","Macao.png"),
        ("Macedonia","Macedonia.png"),
        ("Madagascar","Madagascar.png"),
        ("Malawi","Malawi.png"),
        ("Malaysia","Malaysia.png"),
        ("Maldives","Maldives.png"),
        ("Mali","Mali.png"),
        ("Malta","Malta.png"),
        ("Marshall Islands","Marshall_Islands.png"),
        ("Martinique","Martinique.png"),
        ("Mauritania","Mauritania.png"),
        ("Mauritius","Mauritius.png"),
        ("Mexico","Mexico.png"),
        ("Micronesia","Micronesia.png"),
        ("Moldova","Moldova.png"),
        ("Monaco","Monaco.png"),
        ("Mongolia","Mongolia.png"),
        ("Montserrat","Montserrat.png"),
        ("Morocco","Morocco.png"),
        ("Mozambique","Mozambique.png"),
        ("Myanmar","Myanmar.png"),
        ("Namibia","Namibia.png"),
        ("Nauru","Nauru.png"),
        ("Nepal","Nepal.png"),
        ("Netherlands Antilles","Netherlands_Antilles.png"),
        ("Netherlands","Netherlands.png"),
        ("New Zealand","New_Zealand.png"),
        ("Nicaragua","Nicaragua.png"),
        ("Nigeria","Nigeria.png"),
        ("Niger","Niger.png"),
        ("Niue","Niue.png"),
        ("Norfolk Island","Norfolk_Island.png"),
        ("North Korea","North_Korea.png"),
        ("Norway","Norway.png"),
        ("Oman","Oman.png"),
        ("Pakistan","Pakistan.png"),
        ("Palau","Palau.png"),
        ("Panama","Panama.png"),
        ("Papua New Guinea","Papua_New_Guinea.png"),
        ("Paraguay","Paraguay.png"),
        ("Peru","Peru.png"),
        ("Philippines","Philippines.png"),
        ("Pitcairn Islands","Pitcairn_Islands.png"),
        ("Poland","Poland.png"),
        ("Portugal","Portugal.png"),
        ("Puerto Rico","Puerto_Rico.png"),
        ("Qatar","Qatar.png"),
        ("Republic of the Congo","Republic_of_the_Congo.png"),
        ("Romania","Romania.png"),
        ("Russian Federation","Russian_Federation.png"),
        ("Rwanda","Rwanda.png"),
        ("Saint Kitts and Nevis","Saint_Kitts_and_Nevis.png"),
        ("Saint Lucia","Saint_Lucia.png"),
        ("Saint Pierre","Saint_Pierre.png"),
        ("Saint Vicent and the Grenadines","Saint_Vicent_and_the_Grenadines.png"),
        ("Samoa","Samoa.png"),
        ("San Marino","San_Marino.png"),
        ("Sao Tomé and Príncipe","Sao_Tome_and_Principe.png"),
        ("Saudi Arabia","Saudi_Arabia.png"),
        ("Senegal","Senegal.png"),
        ("Serbia and Montenegro","Serbia_and_Montenegro.png"),
        ("Seychelles","Seychelles.png"),
        ("Sierra Leone","Sierra_Leone.png"),
        ("Singapore","Singapore.png"),
        ("Slovakia","Slovakia.png"),
        ("Slovenia","Slovenia.png"),
        ("Soloman Islands","Soloman_Islands.png"),
        ("Somalia","Somalia.png"),
        ("South Africa","South_Africa.png"),
        ("South Georgia","South_Georgia.png"),
        ("South Korea","South_Korea.png"),
        ("Soviet Union","Soviet_Union.png"),
        ("Spain","Spain.png"),
        ("Sri Lanka","Sri_Lanka.png"),
        ("Sudan","Sudan.png"),
        ("Suriname","Suriname.png"),
        ("Swaziland","Swaziland.png"),
        ("Sweden","Sweden.png"),
        ("Switzerland","Switzerland.png"),
        ("Syria","Syria.png"),
        ("Taiwan","Taiwan.png"),
        ("Tajikistan","Tajikistan.png"),
        ("Tanzania","Tanzania.png"),
        ("Thailand","Thailand.png"),
        ("Tibet","Tibet.png"),
        ("Timor-Leste","Timor-Leste.png"),
        ("Togo","Togo.png"),
        ("Tonga","Tonga.png"),
        ("Trinidad and Tobago","Trinidad_and_Tobago.png"),
        ("Tunisia","Tunisia.png"),
        ("Turkey","Turkey.png"),
        ("Turkmenistan","Turkmenistan.png"),
        ("Turks and Caicos Islands","Turks_and_Caicos_Islands.png"),
        ("Tuvalu","Tuvalu.png"),
        ("UAE","UAE.png"),
        ("Uganda","Uganda.png"),
        ("Ukraine","Ukraine.png"),
        ("United Kingdom","United_Kingdom.png"),
        ("United States of America","United_States_of_America.png"),
        ("Uruguay","Uruguay.png"),
        ("US Virgin Islands","US_Virgin_Islands.png"),
        ("Uzbekistan","Uzbekistan.png"),
        ("Vanuatu","Vanuatu.png"),
        ("Vatican City","Vatican_City.png"),
        ("Venezuela","Venezuela.png"),
        ("Vietnam","Vietnam.png"),
        ("Wallis and Futuna","Wallis_and_Futuna.png"),
        ("Yemen","Yemen.png"),
        ("Zambia","Zambia.png"),
        ("Zimbabwe","Zimbabwe.png")
    ]