NotAuthenticated: You are not authenticated
AlreadyAuthenticated: You are already authenticated
TitlePageNotFound: Request page not located
TitleInternalError: Internal error
TitleAuthRequired: Authentication required
TitleOtherError: Error
BodyOtherError: You're doing it wrong !
BodyAuthRequired: You must be authenticated to access this page
BodyPageNotFound: The page you requested doesn't exist
BodyInternalError: An unknown error occured. Admin has been informed.
SubjectMailVerify: Teaser Insomni'hack 2014 - Verify your email
SubjectMailReset: Teaser Insomni'hack 2014 - Reset your password
BadLoginPassword: Unknown team name or password
UnknownForm: Unknown form error
NeedValidation: You need to validate your account
InvalidUserKey: Invalid user or key
AlreadyVerified: Your team is already verified
ValidationLink: Validation link has been sent
TeamMailExist: Team name or email already used
TeamNotFound: Email not registered
TeamNotVerified: Team not verified
ResetLink: A reset link has been sent to the corresponding email address.
PasswordChanged: Password successfully changed
PasswordsMissmatch: Passwords missmatch
BadFlag: Bad flag
AlreadySolved: Already Solved
WelcomeRegistered: Your team is now registered
BtnSubmit: Submit
BtnReset: Reset
BtnResend: Resend
BtnLogin: Login
RstPassword: Reset Password
RegisterTeam: Register new team
RsndVerifLink: Resend verification link
HScoreboard: Insomni'hack scoreboard
HSubscribe: Register to Insomni'hack CTF
HMessages: Last news !
CTFClosed: Sorry, CTF closed