NotAuthenticated: You are not authenticated
AlreadyAuthenticated: You are already authenticated
TitlePageNotFound: Requested page not found
TitleInternalError: Internal error
TitleAuthRequired: Authentication required
TitleOtherError: Error
BodyOtherError: You're doing something wrong !
BodyAuthRequired: You must be authenticated to access this page
BodyPageNotFound: The page you requested doesn't exist
BodyInternalError: An unknown error occurred. The site admin has been informed.
SubjectMailVerify: Insomni'hack 2015 Teaser - Check your email
SubjectMailReset: Insomni'hack 2015 Teaser - Reset your password
BadLoginPassword: Unknown team name or password
UnknownForm: Unknown form error
NeedValidation: You need to validate your account
InvalidUserKey: Invalid user or key
AlreadyVerified: Your team is already verified
ValidationLink: Validation link has been sent
TeamMailExist: Team name or email already used
TeamNotFound: Email not registered
TeamNotVerified: Team not verified
ResetLink: A reset link has been sent to the corresponding email address.
PasswordChanged: Password successfully changed
PasswordsMissmatch: Passwords mismatch
BadFlag: Bad flag
AlreadySolved: Already Solved
WelcomeRegistered: Your team is now registered
BtnSubmit: Submit
BtnReset: Reset
BtnResend: Resend
BtnLogin: Login
RstPassword: Reset Password
RegisterTeam: Register new team
RsndVerifLink: Resend verification link
HScoreboard: Scoreboard
HSubscribe: Register for the Insomni'hack CTF
HRules: Insomni'hack rules
HMessages: Latest news !
CTFClosed: Sorry, CTF closed
SubscribeTitle: Subscribe
ScoreboardTitle: Scoreboard
NewPasswordTitle: Reset Password
HomeTitle: Insomni'hack 2015 Teaser
RulesTitle: Rules