# NOTE: These settings can be overridden by environment variables as well, in
# particular:
#
#    PGHOST
#    PGPORT
#    PGUSER
#    PGPASS
#    PGDATABASE

Default: &defaults
  user: teaser_inso15
  password:
  host: 127.0.0.1
  port: 5432
  database: teaser_inso15_db
  poolsize: 10

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  database: TeaserInso15_staging
  poolsize: 100
  <<: *defaults

Production:
  user:
  password:
  host:
  port: 5432
  database: inso15
  poolsize: 100
  <<: *defaults
