Default: &defaults
  host: "*4" # any IPv4 host
  port: 3000
  approot: ""
  staticHost: "http://192.168.79.67:3000/static"
  cacheHost: "http://192.168.79.67:3000/"
  copyright: "Teaser Insomni'hack 2015"
  defaultHostname: "http://192.168.79.67:3000"
  TLS: False
  SESFrom:
  SESAccessKey:
  SESSecretKey:
  SESRegion: "eu-west-1"

Development:
  <<: *defaults

Testing:
  staticHost: "http://192.168.79.67/static"
  cacheHost: "http://192.168.79.67/"
  <<: *defaults

Staging:
  <<: *defaults

Production:
  cacheHost: "https://d354firlujjt9e.cloudfront.net/"
  staticHost: "https://dl0kbifbyxlj5.cloudfront.net"
  approot: ""
  TLS: False
  <<: *defaults
